name: Build Docker image and push to hub.docker.com

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '40 23 * * 3'  # Weekly build
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: |
        ls -l
        cd docker
        curl -J -L -u ${{ secrets.LICENSE_ID }}:${{ secrets.LICENSE_KEY }} "https://download.maxmind.com/geoip/databases/GeoLite2-City/download?suffix=tar.gz" -o ./GeoLite2-City.tar.gz && tar xf GeoLite2-City.tar.gz && mv GeoLite2-City_2* GeoLite2-City
        docker build . --file Dockerfile --tag supermasita/geoip-flask:latest
      
    - name: Docker Push
      run: docker push supermasita/geoip-flask
