name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_for_test_files.txt
        pip install -r requirements.txt
    - name: Install GeoIP DB
      run: |
        curl -J -L -u ${{ secrets.LICENSE_ID }}:${{ secrets.LICENSE_KEY }} "https://download.maxmind.com/geoip/databases/GeoLite2-City/download?suffix=tar.gz" -o GeoLite2-City.tar.gz && tar xf GeoLite2-City.tar.gz && mv GeoLite2-City_2* GeoLite2-City
    - name: Test
      run: |
        ls -lh
        python3 app.py &
        sleep 3
        netstat -nat | grep LISTEN
        python3 test/test_app.py
